package com.example.greendaojavatutorial.View

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.content.Intent
import androidx.recyclerview.widget.DefaultItemAnimator
import androidx.recyclerview.widget.LinearLayoutManager
import androidx.recyclerview.widget.RecyclerView
import com.example.greendaojavatutorial.R
import com.example.greendaojavatutorial.Repository
import com.example.greendaojavatutorial.database.User
import kotlinx.android.synthetic.main.activity_main.*

// Entity must be in Java class to use GreenDao
// DaoMaster, DaoSession, UserDao is generated by GreenDao

class MainActivity : AppCompatActivity() {

    private lateinit var listView: RecyclerView
    private lateinit var repository: Repository
    private lateinit var adapter: MyAdapter
    private lateinit var list: MutableList<User>

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        listView = findViewById(R.id.listUser)

        repository = Repository()

        list = ArrayList()

        adapter = MyAdapter(list, this)

        listView.layoutManager = LinearLayoutManager(this)
        listView.setHasFixedSize(true)
        listView.itemAnimator = DefaultItemAnimator()
        listView.adapter = adapter

        inputButton.setOnClickListener {
            val intent = Intent(this@MainActivity, InputActivity::class.java)
            startActivity(intent)
        }
    }

    override fun onStart() {
        super.onStart()
        //clear previous data in list
        list.clear()

        //get data user from database
        list.addAll(repository.getAllData)
        //renew list
        adapter.notifyDataSetChanged()


    }
}
